/* 
 * Swagger Moodle - OpenAPI 3.0
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.11
 * Contact: apiteam@swagger.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ApprovedDegrees
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ApprovedDegreesTests
    {
        // TODO uncomment below to declare an instance variable for ApprovedDegrees
        //private ApprovedDegrees instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ApprovedDegrees
            //instance = new ApprovedDegrees();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ApprovedDegrees
        /// </summary>
        [Test]
        public void ApprovedDegreesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ApprovedDegrees
            //Assert.IsInstanceOfType<ApprovedDegrees> (instance, "variable 'instance' is a ApprovedDegrees");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'CourseId'
        /// </summary>
        [Test]
        public void CourseIdTest()
        {
            // TODO unit test for the property 'CourseId'
        }
        /// <summary>
        /// Test the property 'DegreeId'
        /// </summary>
        [Test]
        public void DegreeIdTest()
        {
            // TODO unit test for the property 'DegreeId'
        }

    }

}
